# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Install tsx for runtime TypeScript execution
RUN npm install tsx

# Copy source files
COPY . .

# The container is configured to run via Smithery startCommand
# as MCP servers require selecting the entrypoint script dynamically
